version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
    #- "my-app/build/**/*"
  base-directory: '/build'
  #discard-paths: yes
