version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre-build:
    commands:
      - npm install
  build:
    commands:
      - npm build
artifacts:
  files:
    - '**/*'
    #- "my-app/build/**/*"
  base-directory: 'my-app/build'
  #discard-paths: yes
